# Generated by Django 4.2.7 on 2023-11-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_countrysafari_tourcategory_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrysafari',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
