# Generated by Django 4.2.7 on 2023-11-14 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_countrysafari_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tour_images'),
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tour_images')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.tourcategory')),
            ],
        ),
    ]
