# Generated by Django 4.2.7 on 2023-11-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourcategory',
            name='highlights',
            field=models.TextField(blank=True, null=True),
        ),
    ]
