# Generated by Django 4.2.7 on 2023-11-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_tourcategory_highlights'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourcategory',
            name='groupSize',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
