# Generated by Django 4.2.7 on 2023-11-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_tourcategory_groupsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourcategory',
            name='languages',
            field=models.CharField(default='English', max_length=50),
        ),
    ]
