# Generated by Django 3.2.23 on 2023-11-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourcategory',
            name='destination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tourcategory',
            name='tour_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
