# Generated by Django 3.2.23 on 2023-11-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20231115_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourcategory',
            name='exclusives',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourcategory',
            name='inclusives',
            field=models.TextField(blank=True, null=True),
        ),
    ]
