# Generated by Django 3.2.23 on 2023-11-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20231115_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('country_of_origin', models.CharField(max_length=100)),
                ('city_of_origin', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('passport_number', models.CharField(max_length=100)),
                ('passport_issue_date', models.DateField()),
                ('passport_expiry_date', models.DateField()),
                ('email2', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('reason_for_travel', models.TextField()),
                ('proposed_day_of_arrival', models.DateField()),
                ('phone_number2', models.CharField(max_length=20)),
                ('home_address', models.CharField(max_length=100)),
                ('address_in_kenya', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('previous_entry', models.BooleanField()),
                ('conviction', models.BooleanField()),
                ('passport_image', models.ImageField(upload_to='')),
                ('passport_data_page', models.FileField(upload_to='')),
                ('passport_front_cover', models.FileField(upload_to='')),
                ('invitation_letter', models.FileField(upload_to='')),
                ('aknowledge', models.BooleanField(default=False)),
                ('declaration', models.BooleanField(default=False)),
            ],
        ),
    ]
