# Generated by Django 5.0 on 2023-12-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_visa"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name="visa",
            name="aknowledge",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="visa",
            name="declaration",
            field=models.BooleanField(),
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.ManyToManyField(to="base.tourcategory")),
            ],
        ),
    ]
