# Generated by Django 5.0 on 2023-12-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_booking_alter_visa_aknowledge_alter_visa_declaration_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="item",
            new_name="trips",
        ),
        migrations.AddField(
            model_name="cart",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
