# Generated by Django 5.0 on 2024-01-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0018_alter_boookingpayments_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visa",
            name="invitation_letter",
            field=models.FileField(upload_to="visa_docs"),
        ),
        migrations.AlterField(
            model_name="visa",
            name="passport_data_page",
            field=models.FileField(upload_to="visa_docs"),
        ),
        migrations.AlterField(
            model_name="visa",
            name="passport_front_cover",
            field=models.FileField(upload_to="visa_docs"),
        ),
        migrations.AlterField(
            model_name="visa",
            name="passport_image",
            field=models.ImageField(upload_to="visa_docs"),
        ),
    ]
