# Generated by Django 5.0 on 2024-01-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_visa_phone_number2_visa_departure_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visa',
            name='conviction',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=3),
        ),
    ]
