# Generated by Django 5.0 on 2024-01-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_visa_conviction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visa',
            name='previous_entry',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=3),
        ),
    ]
